-- Seed books data
INSERT INTO books (title, author, category, brand, price, rating, reviews, image, description, tags) VALUES
('The Midnight Library',          'Matt Haig',            'fiction',     'penguin',    12.99, 4.7, 2341, 'https://picsum.photos/seed/book1/300/400',  'A dazzling novel about all the choices that go into a life well lived.',                    ARRAY['bestseller','new']),
('Atomic Habits',                 'James Clear',          'self-help',   'penguin',    14.99, 4.9, 5120, 'https://picsum.photos/seed/book2/300/400',  'Tiny changes, remarkable results. The definitive guide to building good habits.',          ARRAY['bestseller']),
('Sapiens',                       'Yuval Noah Harari',    'history',     'harpercol',  13.99, 4.8, 4200, 'https://picsum.photos/seed/book3/300/400',  'A brief history of humankind from the Stone Age to the present.',                          ARRAY['bestseller']),
('The Lean Startup',              'Eric Ries',            'business',    'macmillan',  11.99, 4.5, 1890, 'https://picsum.photos/seed/book4/300/400',  'How constant innovation creates radically successful businesses.',                         ARRAY[]::TEXT[]),
('Clean Code',                    'Robert C. Martin',     'science',     'oreilly',    19.99, 4.6, 3100, 'https://picsum.photos/seed/book5/300/400',  'A handbook of agile software craftsmanship.',                                              ARRAY['new']),
('Pride and Prejudice',           'Jane Austen',          'romance',     'penguin',     6.99, 4.8, 6700, 'https://picsum.photos/seed/book6/300/400',  'The classic tale of love, society, and misunderstanding.',                                 ARRAY['classic']),
('Harry Potter & the Sorcerer''s Stone', 'J.K. Rowling', 'children',    'scholastic',  9.99, 4.9, 9800, 'https://picsum.photos/seed/book7/300/400',  'The magical story that started it all.',                                                   ARRAY['bestseller','classic']),
('A Brief History of Time',       'Stephen Hawking',      'science',     'macmillan',  10.99, 4.7, 3400, 'https://picsum.photos/seed/book8/300/400',  'From the Big Bang to black holes — science made accessible.',                              ARRAY['classic']),
('The Great Gatsby',              'F. Scott Fitzgerald',  'fiction',     'penguin',     7.99, 4.4, 5500, 'https://picsum.photos/seed/book9/300/400',  'The quintessential Jazz Age novel of wealth and longing.',                                 ARRAY['classic']),
('Thinking, Fast and Slow',       'Daniel Kahneman',      'non-fiction', 'macmillan',  13.49, 4.6, 2800, 'https://picsum.photos/seed/book10/300/400', 'How two systems drive the way we think and make choices.',                                 ARRAY[]::TEXT[]),
('The Alchemist',                 'Paulo Coelho',         'fiction',     'harpercol',   8.99, 4.7, 7200, 'https://picsum.photos/seed/book11/300/400', 'A philosophical novel about following your dreams.',                                       ARRAY['bestseller']),
('Zero to One',                   'Peter Thiel',          'business',    'macmillan',  12.49, 4.5, 2100, 'https://picsum.photos/seed/book12/300/400', 'Notes on startups, or how to build the future.',                                           ARRAY['new']),
('The Power of Now',              'Eckhart Tolle',        'self-help',   'harpercol',  11.49, 4.6, 3300, 'https://picsum.photos/seed/book13/300/400', 'A guide to spiritual enlightenment and living in the present.',                            ARRAY[]::TEXT[]),
('Dune',                          'Frank Herbert',        'fiction',     'macmillan',  14.49, 4.8, 4800, 'https://picsum.photos/seed/book14/300/400', 'The epic science-fiction saga of desert planet Arrakis.',                                  ARRAY['bestseller','classic']),
('JavaScript: The Good Parts',    'Douglas Crockford',    'science',     'oreilly',    16.99, 4.4, 1700, 'https://picsum.photos/seed/book15/300/400', 'Unearthing the excellence in JavaScript.',                                                 ARRAY[]::TEXT[]),
('Educated',                      'Tara Westover',        'non-fiction', 'penguin',    12.99, 4.8, 4100, 'https://picsum.photos/seed/book16/300/400', 'A memoir about the transformative power of education.',                                    ARRAY['new'])
ON CONFLICT DO NOTHING;
